var index="<a class='a1' style='cursor:progress' href= '../index.html'>Main Page</a>";
var games="<a class='a1' style='cursor:progress' href= '../games.html'>Games</a>";
var news="<a class='a1' style='cursor:progress' href= '../news.html'>News</a>";
var links="<a class='a1' style='cursor:progress' href= '../links.html'>Links</a>";
var downloads="<a class='a1' style='cursor:progress' href= '../downloads.html'>Downloads</a>";
var audio="<a class='a1' style='cursor:progress' href= '../audio.html'>Audio</a>";
var gallery="<a class='a1' style='cursor:progress' href= '../gallery.html'>Gallery</a>";
var videos="<a class='a1' style='cursor:progress' href= '../videos.html'>Videos</a>";
var emulator="<a class='a1' style='cursor:progress' href= '../emulators.html'>Emulators</a>";
var shop="<a class='a1' style='cursor:progress' href= '../shop.html'>Shop</a>";
var saobr="<a class='a1' style='cursor:progress' href= '../saobr.html'>SAOBR</a>";
 document.write(index);
 document.write(games);
 document.write(news);
 document.write(links);
 document.write(downloads);
 document.write(audio);
 document.write(gallery);
 document.write(videos);
 document.write(emulator);
 document.write(shop);
 document.write(saobr);
