var main="<a class='a2' style='cursor:progress' href= 'gallery.html'>Main Gallery</a>";
var notepad="<a class='a2' style='cursor:progress' href= 'notepad.html'>Notepad++</a>";
var gifs="<a class='a2' style='cursor:progress' href= 'gifs.html'>Gifs</a>";
var fatman="<a class='a2' style='cursor:progress' href= 'fatman.html'>Fatman TM</a>";
var mark="<a class='a2' style='cursor:progress' href= 'mark.html'>Mark TM</a>";
var ads="<a class='a2' style='cursor:progress' href= 'ads.html'>Ads</a>";
var unity="<a class='a2' style='cursor:progress' href= 'unity assets.html'>Unity Assets</a>";
var emuimgs="<a class='a2' style='cursor:progress' href= 'emulatorimages.html'>Emulators</a>";
var prephotoshop="<a class='a2' style='cursor:progress' href= 'prephotoshop.html'>Pre Photoshop</a>";
var games="<a class='a2' style='cursor:progress' href= 'game images.html'>Games</a>";
var thumbnails="<a class='a2' style='cursor:progress' href= 'thumbnails.html'>Thumbnails</a>";
var psdandxcf="<a class='a2' style='cursor:progress' href= 'psd and xcf files.html'>PSD XCF</a>";
document.write(main);
document.write(notepad);
document.write(gifs);
document.write(fatman);
document.write(mark);
document.write(ads);
document.write(unity);
document.write(emuimgs);
document.write(prephotoshop);
document.write(games);
document.write(thumbnails);
document.write(psdandxcf);
