var index="<a class='a1' style='cursor:progress' href= '../../index.html'>Main Page</a>";
var games="<a class='a1' style='cursor:progress' href= '../../games.html'>Games</a>";
var news="<a class='a1' style='cursor:progress' href= '../../news.html'>News</a>";
var links="<a class='a1' style='cursor:progress' href= '../../links.html'>Links</a>";
var downloads="<a class='a1' style='cursor:progress' href= '../../downloads.html'>Downloads</a>";
var audio="<a class='a1' style='cursor:progress' href= '../../audio.html'>Audio</a>";
var gallery="<a class='a1' style='cursor:progress' href= '../../gallery.html'>Gallery</a>";
var videos="<a class='a1' style='cursor:progress' href= '../../videos.html'>Videos</a>";
var emulator="<a class='a1' style='cursor:progress' href= '../../emulators.html'>Emulators</a>";
var shop="<a class='a1' style='cursor:progress' href= '../../shop.html'>Shop</a>";
var saobr="<a class='a1' style='cursor:progress' href= '../../saobr.html'>SAOBR</a>";
var three="<a class='a1' style='cursor:progress' href= '../../3d.html'>3D</a>";
var histor="<a class='a1' style='cursor:progress' href= '../../history.html'>History</a>";
var seasonal="<a class='a10' style='cursor:progress' href= '../../seasonal.html'>Seasonal</a>";
var contact="<br><a class='a1' style='cursor:progress' href= '../../contact.html'>Contact</a>";
var faq="<a class='a1' style='cursor:progress' href= '../../faq.html'>F.A.Q.</a>";
var unblocker="<a class='a1' style='cursor:progress' href= '../../unblocker.html'>Unblocker</a>";
 document.write(index);
 document.write(games);
 document.write(news);
 document.write(links);
 document.write(downloads);
 document.write(audio);
 document.write(gallery);
 document.write(videos);
 document.write(emulator);
 document.write(shop);
 document.write(saobr);
 document.write(three);
 document.write(histor);
 document.write(seasonal);
 document.write(contact);
 document.write(faq);
 document.write(unblocker);
